<a href="https://colab.research.google.com/github/alessandro54/challenge/blob/main/Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re

## First exercise

In [ ]:
# First we clear the data doing an split and ignoring short lines
lines = [x for x in open('w_data.dat', 'r') if len(x.split()) > 9]

In [ ]:
df = pd.DataFrame(
                [x.split()[:3] for x in lines[1:]],
                index=range(1,len(lines)),
                columns=lines[0].split()[:3])

In [ ]:
# Replacing asteriscs
df['MxT'] = df['MxT'].replace('\*', '', regex=True).astype(float)

In [ ]:
df.loc[df['MxT'] == df['MxT'].max()]

    Dy   MxT MnT
26  26  97.0  64

Day 26 is the one with the highest temperature

In [ ]:
df['MnT'] = df['MnT'].replace('\*', '', regex=True).astype(float)

In [ ]:
df.loc[df['MnT'] == df['MnT'].min()]

  Dy   MxT   MnT
9  9  86.0  32.0

Day 9 is the one with the lowest temperature

## Second exercise

In [ ]:
soccer_lines = [x for x in open('soccer.dat', 'r') if len(x.split()) > 1]

In [ ]:
# Cleaning lines
soccer_lines = [re.sub('-', '', x) for x in soccer_lines]

In [ ]:
df = pd.DataFrame(
                [x.split()[1:] for x in soccer_lines[1:]],
                columns=soccer_lines[0].split())

In [ ]:
# Converting cols to int

df['F'] = df['F'].astype(int)
df['A'] = df['A'].astype(int)

In [ ]:
# Creating a new column with the difference
df['GDIFF'] = abs(df['F'] - df['A'])

In [ ]:
df.loc[df['GDIFF'] == df['GDIFF'].min()]

          Team   P   W   L   D   F   A Pts  GDIFF
7  Aston_Villa  38  12  14  12  46  47  50      1

Aston Villa has the least goals difference